export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_PENDING = 'SIGNUP_USER_PENDING';
export const SIGNUP_USER_FULFILLED = 'SIGNUP_USER_FULFILLED';
export const SIGNUP_USER_REJECTED = 'SIGNUP_USER_REJECTED';

export const RESET_USER_ALREADY_REGISTERED_ERROR = 'RESET_USER_ALREADY_REGISTERED_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const HIDE_LOGOUT_BUTTON = 'HIDE_LOGOUT_BUTTON';
export const SHOW_LOGOUT_BUTTON = 'SHOW_LOGOUT_BUTTON';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_PASSWORD_RESET_TOKEN = 'GET_PASSWORD_RESET_TOKEN';
export const GET_PASSWORD_RESET_TOKEN_PENDING = 'GET_PASSWORD_RESET_TOKEN_PENDING';
export const GET_PASSWORD_RESET_TOKEN_FULFILLED = 'GET_PASSWORD_RESET_TOKEN_FULFILLED';
export const GET_PASSWORD_RESET_TOKEN_REJECTED = 'GET_PASSWORD_RESET_TOKEN_REJECTED';

export const CLEAR_PASSWORD_RESET_DATA = 'CLEAR_PASSWORD_RESET_DATA';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_PENDING = 'RESET_PASSWORD_PENDING';
export const RESET_PASSWORD_FULFILLED = 'RESET_PASSWORD_FULFILLED';
export const RESET_PASSWORD_REJECTED = 'RESET_PASSWORD_REJECTED';

export const RESET_LOGIN_ERROR = 'RESET_LOGIN_ERROR';

export const AUTH_REDUCER_STATE_RESETTER = 'AUTH_REDUCER_STATE_RESETTER';