export const GET_ALL_AVAILABLE_JOBS_FOR_CANDIDATE = 'GET_ALL_AVAILABLE_JOBS_FOR_CANDIDATE';
export const GET_ALL_AVAILABLE_JOBS_FOR_CANDIDATE_PENDING = 'GET_ALL_AVAILABLE_JOBS_FOR_CANDIDATE_PENDING';
export const GET_ALL_AVAILABLE_JOBS_FOR_CANDIDATE_FULFILLED = 'GET_ALL_AVAILABLE_JOBS_FOR_CANDIDATE_FULFILLED';
export const GET_ALL_AVAILABLE_JOBS_FOR_CANDIDATE_REJECTED = 'GET_ALL_AVAILABLE_JOBS_FOR_CANDIDATE_REJECTED';


export const GET_APPLIED_JOBS_FOR_CANDIDATE = 'GET_APPLIED_JOBS_FOR_CANDIDATE';
export const GET_APPLIED_JOBS_FOR_CANDIDATE_PENDING = 'GET_APPLIED_JOBS_FOR_CANDIDATE_PENDING';
export const GET_APPLIED_JOBS_FOR_CANDIDATE_FULFILLED = 'GET_APPLIED_JOBS_FOR_CANDIDATE_FULFILLED';
export const GET_APPLIED_JOBS_FOR_CANDIDATE_REJECTED = 'GET_APPLIED_JOBS_FOR_CANDIDATE_REJECTED';


export const CANDIDATE_APPLY_TO_JOB = 'CANDIDATE_APPLY_TO_JOB';
export const CANDIDATE_APPLY_TO_JOB_PENDING = 'CANDIDATE_APPLY_TO_JOB_PENDING';
export const CANDIDATE_APPLY_TO_JOB_FULFILLED = 'CANDIDATE_APPLY_TO_JOB_FULFILLED';
export const CANDIDATE_APPLY_TO_JOB_REJECTED = 'CANDIDATE_APPLY_TO_JOB_REJECTED';

export const POST_NEW_JOB = 'POST_NEW_JOB';
export const POST_NEW_JOB_PENDING = 'POST_NEW_JOB_PENDING';
export const POST_NEW_JOB_FULFILLED = 'POST_NEW_JOB_FULFILLED';
export const POST_NEW_JOB_REJECTED = 'POST_NEW_JOB_REJECTED';

export const GET_POSTED_JOBS = 'GET_POSTED_JOBS';
export const GET_POSTED_JOBS_PENDING = 'GET_POSTED_JOBS_PENDING';
export const GET_POSTED_JOBS_FULFILLED = 'GET_POSTED_JOBS_FULFILLED';
export const GET_POSTED_JOBS_REJECTED = 'GET_POSTED_JOBS_REJECTED';

export const GET_PARTICULAR_JOB_CANDIDATES = 'GET_PARTICULAR_JOB_CANDIDATES';
export const GET_PARTICULAR_JOB_CANDIDATES_PENDING = 'GET_PARTICULAR_JOB_CANDIDATES_PENDING';
export const GET_PARTICULAR_JOB_CANDIDATES_FULFILLED = 'GET_PARTICULAR_JOB_CANDIDATES_FULFILLED';
export const GET_PARTICULAR_JOB_CANDIDATES_REJECTED = 'GET_PARTICULAR_JOB_CANDIDATES_REJECTED';

export const JOBS_REDUCER_STATE_RESETTER = 'JOBS_REDUCER_STATE_RESETTER';